<h1> Telecom Company Churn Rate, Call Center Data

In this project, I will perform some Data cleaning to removes data that does not belong in the dataset. I will be scrubbing, identifing and fixes errors, duplicates, and irrelevant data from a raw Churn rate data set for a telecom company.

Analyzing churn rate data alongside call center data can provide valuable insights into customer behavior, satisfaction levels, and potential areas for improvement within a telecom company. Combining churn rate data with call center data offers a comprehensive view of customer dynamics and can guide strategic decision-making aimed at reducing churn and improving overall customer satisfaction and retention.

<h1> Import Libraries

In [1]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
print(os.getcwd())

C:\Users\dshaw\Springboard\Capstone Two - churn data

<h1> Objectives

1. What kind of cleaning steps did you perform?
2. How did you deal with missing values, if there were any?
3. Were there outliers, and how did you handle them?

<h1> Load the Telecom Churn Rate data

In [3]:
churn_rate = pd.read_excel("Telecom Churn Rate Dataset.xlsx")

In [3]:
churn_rate.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 23 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer ID        7043 non-null   object
 1   gender             7043 non-null   object
 2   Senior Citizen     7043 non-null   int64
 3   Partner            7043 non-null   object
 4   Dependents         7043 non-null   object
 5   tenure             7043 non-null   int64
 6   Phone Service      7043 non-null   object
 7   Multiple Lines     7043 non-null   object
 8   Internet Service   7043 non-null   object
 9   Online Security    7043 non-null   object
 10  Online Backup      7043 non-null   object
 11  Device Protection  7043 non-null   object
 12  Tech Support       7043 non-null   object
 13  Streaming TV       7043 non-null   object
 14  Streaming Movies   7043 non-null   object
 15  Contract           7043 non-null   object
 16  Paperless Billing  7043 non-null   object
 17  Payment Method     7043 non-null   object
 18  Monthly Charges    7043 non-null   float64
 19  Total Charges      7043 non-null   object
 20  num AdminTickets   7043 non-null   int64
 21  num TechTickets    7043 non-null   int64
 22  Churn              7043 non-null   object
dtypes: float64(1), int64(4), object(18)
memory usage: 1.2+ MB

In [4]:
churn_rate.head()

,customer ID,gender,Senior Citizen,Partner,Dependents,tenure,Phone Service,Multiple Lines,Internet Service,Online Security,...,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,num AdminTickets,num TechTickets,Churn
0,7590-VHVEG,Female,0,Yes,no,1,No,No phone service,DSL,No,...,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,0,0,No
1,5575-GNVDE,Male,0,No,no,34,Yes,No,DSL,Yes,...,No,No,One year,No,Mailed check,56.95,1889.5,0,0,No
2,3668-QPYBK,Male,0,No,no,2,Yes,No,DSL,Yes,...,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,0,0,Yes
3,7795-CFOCW,Male,0,No,no,45,No,No phone service,DSL,Yes,...,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,0,3,No
4,9237-HQITU,Female,0,No,no,2,Yes,No,Fiber optic,No,...,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,0,0,Yes

<h1> Categorical data

In [5]:
churn_rate.select_dtypes(object)

,customer ID,gender,Partner,Dependents,Phone Service,Multiple Lines,Internet Service,Online Security,Online Backup,Device Protection,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Total Charges,Churn
0,7590-VHVEG,Female,Yes,no,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,No
1,5575-GNVDE,Male,No,no,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,1889.5,No
2,3668-QPYBK,Male,No,no,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,108.15,Yes
3,7795-CFOCW,Male,No,no,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),1840.75,No
4,9237-HQITU,Female,No,no,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,Yes,yes,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,1990.5,No
7039,2234-XADUH,Female,Yes,yes,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),7362.9,No
7040,4801-JZAZL,Female,Yes,yes,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,346.45,No
7041,8361-LTMKD,Male,Yes,no,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,306.6,Yes
7042,3186-AJIEK,Male,No,no,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),6844.5,No

In [6]:
#churn_rate[churn_rate['customer ID'] == '7590-VHVEG'].T

<h1> Capitalize column names

In [7]:
churn_rate['Dependents'] = churn_rate['Dependents'].str.title()

In [8]:
churn_rate

,customer ID,gender,Senior Citizen,Partner,Dependents,tenure,Phone Service,Multiple Lines,Internet Service,Online Security,...,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,num AdminTickets,num TechTickets,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,0,0,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,No,No,One year,No,Mailed check,56.95,1889.5,0,0,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,0,0,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,0,3,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,0,0,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,0,0,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,0,5,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,0,0,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,0,0,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,2,0,No

<h1> Cleaning the data

In [9]:
# change Total Charges to float

In [10]:
churn_rate['Total Charges'] = pd.to_numeric(churn_rate['Total Charges'], errors='coerce')

<h1> Missing data

In [11]:
# check to see if you have any missing values

In [12]:
churn_rate.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 23 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer ID        7043 non-null   object
 1   gender             7043 non-null   object
 2   Senior Citizen     7043 non-null   int64
 3   Partner            7043 non-null   object
 4   Dependents         7043 non-null   object
 5   tenure             7043 non-null   int64
 6   Phone Service      7043 non-null   object
 7   Multiple Lines     7043 non-null   object
 8   Internet Service   7043 non-null   object
 9   Online Security    7043 non-null   object
 10  Online Backup      7043 non-null   object
 11  Device Protection  7043 non-null   object
 12  Tech Support       7043 non-null   object
 13  Streaming TV       7043 non-null   object
 14  Streaming Movies   7043 non-null   object
 15  Contract           7043 non-null   object
 16  Paperless Billing  7043 non-null   object
 17  Payment Method     7043 non-null   object
 18  Monthly Charges    7043 non-null   float64
 19  Total Charges      7032 non-null   float64
 20  num AdminTickets   7043 non-null   int64
 21  num TechTickets    7043 non-null   int64
 22  Churn              7043 non-null   object
dtypes: float64(2), int64(4), object(17)
memory usage: 1.2+ MB

<h1> Number Of Missing Values By Column

In [13]:
churn_rate.isna().sum()

customer ID           0
gender                0
Senior Citizen        0
Partner               0
Dependents            0
tenure                0
Phone Service         0
Multiple Lines        0
Internet Service      0
Online Security       0
Online Backup         0
Device Protection     0
Tech Support          0
Streaming TV          0
Streaming Movies      0
Contract              0
Paperless Billing     0
Payment Method        0
Monthly Charges       0
Total Charges        11
num AdminTickets      0
num TechTickets       0
Churn                 0
dtype: int64

In [14]:
missing = pd.concat([churn_rate.isnull().sum(), 100 * churn_rate.isnull().mean()], axis=1)
missing.columns=['Count', '%']
missing.sort_values(by='Count', ascending=False)

                   Count         %
Total Charges         11  0.156183
customer ID            0  0.000000
Tech Support           0  0.000000
num TechTickets        0  0.000000
num AdminTickets       0  0.000000
Monthly Charges        0  0.000000
Payment Method         0  0.000000
Paperless Billing      0  0.000000
Contract               0  0.000000
Streaming Movies       0  0.000000
Streaming TV           0  0.000000
Device Protection      0  0.000000
gender                 0  0.000000
Online Backup          0  0.000000
Online Security        0  0.000000
Internet Service       0  0.000000
Multiple Lines         0  0.000000
Phone Service          0  0.000000
tenure                 0  0.000000
Dependents             0  0.000000
Partner                0  0.000000
Senior Citizen         0  0.000000
Churn                  0  0.000000

In [15]:
# Each missing value by row

In [16]:
churn_rate_Total_Charges = churn_rate[churn_rate.isna().any(axis=1)]
print(churn_rate_Total_Charges)

     customer ID  gender  Senior Citizen Partner Dependents  tenure  \
488   4472-LVYGI  Female               0     Yes        Yes       0
753   3115-CZMZD    Male               0      No        Yes       0
936   5709-LVOEQ  Female               0     Yes        Yes       0
1082  4367-NUYAO    Male               0     Yes        Yes       0
1340  1371-DWPAZ  Female               0     Yes        Yes       0
3331  7644-OMVMY    Male               0     Yes        Yes       0
3826  3213-VVOLG    Male               0     Yes        Yes       0
4380  2520-SGTTA  Female               0     Yes        Yes       0
5218  2923-ARZLG    Male               0     Yes        Yes       0
6670  4075-WKNIU  Female               0     Yes        Yes       0
6754  2775-SEFEE    Male               0      No        Yes       0

     Phone Service    Multiple Lines Internet Service      Online Security  \
488             No  No phone service              DSL                  Yes
753            Yes                No               No  No internet service
936            Yes                No              DSL                  Yes
1082           Yes               Yes               No  No internet service
1340            No  No phone service              DSL                  Yes
3331           Yes                No               No  No internet service
3826           Yes               Yes               No  No internet service
4380           Yes                No               No  No internet service
5218           Yes                No               No  No internet service
6670           Yes               Yes              DSL                   No
6754           Yes               Yes              DSL                  Yes

      ...         Streaming TV     Streaming Movies  Contract  \
488   ...                  Yes                   No  Two year
753   ...  No internet service  No internet service  Two year
936   ...                  Yes                  Yes  Two year
1082  ...  No internet service  No internet service  Two year
1340  ...                  Yes                   No  Two year
3331  ...  No internet service  No internet service  Two year
3826  ...  No internet service  No internet service  Two year
4380  ...  No internet service  No internet service  Two year
5218  ...  No internet service  No internet service  One year
6670  ...                  Yes                   No  Two year
6754  ...                   No                   No  Two year

     Paperless Billing             Payment Method Monthly Charges  \
488                Yes  Bank transfer (automatic)           52.55
753                 No               Mailed check           20.25
936                 No               Mailed check           80.85
1082                No               Mailed check           25.75
1340                No    Credit card (automatic)           56.05
3331                No               Mailed check           19.85
3826                No               Mailed check           25.35
4380                No               Mailed check           20.00
5218               Yes               Mailed check           19.70
6670                No               Mailed check           73.35
6754               Yes  Bank transfer (automatic)           61.90

     Total Charges num AdminTickets  num TechTickets  Churn
488            NaN                0                0     No
753            NaN                5                0     No
936            NaN                0                0     No
1082           NaN                1                0     No
1340           NaN                0                0     No
3331           NaN                0                0     No
3826           NaN                0                0     No
4380           NaN                5                0     No
5218           NaN                0                0     No
6670           NaN                0                0     No
6754           NaN                0                0     No

[11 rows x 23 columns]

<h1> Replace Total Charges with statistical mean

In [17]:
total_charges_mean = churn_rate['Total Charges'].mean()

In [18]:
churn_rate_new = churn_rate.fillna({'Total Charges': total_charges_mean})

In [19]:
churn_rate_new.isna().sum()

customer ID          0
gender               0
Senior Citizen       0
Partner              0
Dependents           0
tenure               0
Phone Service        0
Multiple Lines       0
Internet Service     0
Online Security      0
Online Backup        0
Device Protection    0
Tech Support         0
Streaming TV         0
Streaming Movies     0
Contract             0
Paperless Billing    0
Payment Method       0
Monthly Charges      0
Total Charges        0
num AdminTickets     0
num TechTickets      0
Churn                0
dtype: int64

<h1> Unique Customer ID

In [20]:
churn_rate['customer ID'].value_counts().head()

customer ID
7590-VHVEG    1
3791-LGQCY    1
6008-NAIXK    1
5956-YHHRX    1
5365-LLFYV    1
Name: count, dtype: int64

In [21]:
# list unique for each column

In [22]:
for x in churn_rate_new:
    unique_columns = churn_rate_new[x].unique()
    print(x, "-", unique_columns)

customer ID - ['7590-VHVEG' '5575-GNVDE' '3668-QPYBK' ... '4801-JZAZL' '8361-LTMKD'
 '3186-AJIEK']
gender - ['Female' 'Male']
Senior Citizen - [0 1]
Partner - ['Yes' 'No']
Dependents - ['No' 'Yes']
tenure - [ 1 34  2 45  8 22 10 28 62 13 16 58 49 25 69 52 71 21 12 30 47 72 17 27
  5 46 11 70 63 43 15 60 18 66  9  3 31 50 64 56  7 42 35 48 29 65 38 68
 32 55 37 36 41  6  4 33 67 23 57 61 14 20 53 40 59 24 44 19 54 51 26  0
 39]
Phone Service - ['No' 'Yes']
Multiple Lines - ['No phone service' 'No' 'Yes']
Internet Service - ['DSL' 'Fiber optic' 'No']
Online Security - ['No' 'Yes' 'No internet service']
Online Backup - ['Yes' 'No' 'No internet service']
Device Protection - ['No' 'Yes' 'No internet service']
Tech Support - ['No' 'Yes' 'No internet service']
Streaming TV - ['No' 'Yes' 'No internet service']
Streaming Movies - ['No' 'Yes' 'No internet service']
Contract - ['Month-to-month' 'One year' 'Two year']
Paperless Billing - ['Yes' 'No']
Payment Method - ['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']
Monthly Charges - [29.85 56.95 53.85 ... 63.1  44.2  78.7 ]
Total Charges - [  29.85 1889.5   108.15 ...  346.45  306.6  6844.5 ]
num AdminTickets - [0 1 5 2 4 3]
num TechTickets - [0 3 2 4 1 6 5 7 8 9]
Churn - ['No' 'Yes']

<h1> Find any Duplicates

In [23]:
churn_rate.duplicated(subset= ['customer ID'], keep='first')

0       False
1       False
2       False
3       False
4       False
        ...
7038    False
7039    False
7040    False
7041    False
7042    False
Length: 7043, dtype: bool

In [24]:
# there are no duplicates

<h1> New index

In [25]:
churn_rate_newind = churn_rate.set_index('customer ID')

In [26]:
churn_rate_newind.head()

,gender,Senior Citizen,Partner,Dependents,tenure,Phone Service,Multiple Lines,Internet Service,Online Security,Online Backup,...,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,num AdminTickets,num TechTickets,Churn
customer ID,,,,,,,,,,,,,,,,,,,,,
7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,...,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,0,0,No
5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,No,...,No,No,One year,No,Mailed check,56.95,1889.50,0,0,No
3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,...,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,0,0,Yes
7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,No,...,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,0,3,No
9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,No,...,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,0,0,Yes

## Save data

In [ ]:
# save the data to a new csv file
datapath = '../data'
save_file(ski_data, 'ski_data_cleaned.csv', datapath)